
# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

# SUPER key
$mainMod = SUPER

# Actions
bind = $mainMod, RETURN, exec, kitty # Open kitty
bind = $mainMod, B, exec, /usr/bin/google-chrome-stable # Open browser
bind = $mainMod, E, exec, /usr/bin/thunar # Open file manager
bind = $mainMod, L, exec, hyprlock

bind = $mainMod, C, killactive
bind = $mainMod, T, togglefloating # Toggle between tiling and floating window
bind = $mainMod, F, fullscreen # Open the window in fullscreen
bind = $mainMod, SPACE, exec, rofi -show drun # Open rofi

bind = $mainMod, P, pseudo # dwindle
bind = $mainMod, J, togglesplit # dwindle

# Volume and Brightness controls (added $mainMod modifier)
bind = $mainMod, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%+
bind = $mainMod, XF86AudioLowerVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%-
bind = $mainMod, XF86MonBrightnessUp, exec, brightnessctl set 10%+
bind = $mainMod, XF86MonBrightnessDown, exec, brightnessctl set 10%-
bind = $mainMod, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = $mainMod, XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bind = $mainMod, XF86WLAN, exec, nmcli radio wifi toggle
bind = $mainMod, XF86Refresh, exec, xdotool key F5

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l # Move focus left
bind = $mainMod, right, movefocus, r # Move focus right
bind = $mainMod, up, movefocus, u # Move focus up
bind = $mainMod, down, movefocus, d # Move focus down

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1 # Switch to workspace 1
bind = $mainMod, 2, workspace, 2 # Switch to workspace 2
bind = $mainMod, 3, workspace, 3 # Switch to workspace 3
bind = $mainMod, 4, workspace, 4 # Switch to workspace 4
bind = $mainMod, 5, workspace, 5 # Switch to workspace 5

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1 # Move window to workspace 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2 # Move window to workspace 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3 # Move window to workspace 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4 # Move window to workspace 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5 # Move window to workspace 5

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, Button4, workspace, e+1 # Mouse scroll up (increase workspace)
bind = $mainMod, Button5, workspace, e-1 # Mouse scroll down (decrease workspace)

# Keybinding to move window
bindm = $mainMod, mouse:272, movewindow
# Keybinding to resize window
bindm = $mainMod, mouse:273, resizewindow










